version: '3.8'

services:
  ingest:
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    volumes:
      - ./data:/home/jovyan/data
      - ./scripts:/home/jovyan/scripts
    command: python /home/jovyan/scripts/bronze.py

  transform_silver:
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    depends_on:
      ingest:
        condition: service_completed_successfully
    volumes:
      - ./data:/home/jovyan/data
      - ./scripts:/home/jovyan/scripts
    # Este serviço roda o Spark para criar a camada Silver
    command: python /home/jovyan/scripts/silver.py

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.pyspark
    container_name: jupyter-spark
    depends_on:
      transform_silver:
        condition: service_completed_successfully
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_SUBMIT_ARGS=--master local[*] pyspark-shell